package mz.co.mefemasys.xicola.backend.models;

public enum ERole {
    ROLE_USER,
    ROLE_MODERATOR,
    ROLE_ADMIN,
    ROLE_ESTUDANTE,
    ROLE_PROFESSOR,
    ROLE_BIBLIOTECARIO,
    ROLE_FINANCEIRO,
    ROLE_PEDAGOGICO,
    ROLE_AQUISICOES,
    ROLE_DIRECTOR,
    ROLE_ENCARREGADO,
    ROLE_SECRETARIA,

}
